ARG NODE_VERSION=18.15-alpine3.17

FROM node:$NODE_VERSION as deps

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

FROM node:$NODE_VERSION as build

WORKDIR /usr/src/app

USER node

COPY --from=deps --chown=node:node /usr/src/app/node_modules ./node_modules/
COPY src/ ./src/
COPY public/ ./public/
COPY package*.json ./
COPY tsconfig.json .


CMD ["npm", "start"]